name: money_snap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  mobx_codegen: ^2.6.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
